### ISSUE TITLE
Define `Automatic-Module-Name` in manifest

### ISSUE THREAD

**Issue by NeilMadden** [c-rack/cbor-java#147]
When including cbor-java as a dependency of a project using Java 9 modules, the build process produces the following warning:

```
[WARNING] ************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [cbor-0.9.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] ************************************************************************************************************************************
```

This is because Java will convert the jar file to an [automatic module](https://stackoverflow.com/questions/46741907/what-is-an-automatic-module), whose name is based on the name of the jar file itself, which is (apparently) not guaranteed to be the same across build systems.

From what I gather, the solution - assuming you don't want to move to modules yourself - is to add an `Automatic-Module-Name` entry to the jar's manifest that specifies an explicit name to be used in this case. I think something like the following should work:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.2.2</version>
    <configuration>
        <archive>
            <manifestEntries>
                <Automatic-Module-Name>co.nstant.in.cbor</Automatic-Module-Name>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>
```

As I understand it, this will ensure a consistent automatic module name for any consumers using Java platform modules, without forcing you to adopt modules yourself.

**Comment by c-rack** [comment]
@NeilMadden Thank you for opening this issue! If you send a PR, I'll merge it asap.
