### ISSUE TITLE
High-level layer

### ISSUE THREAD

**Issue by neothemachine** [c-rack/cbor-java#15]
I was wondering if it would make sense to add optional functionality where the input of encoding and output of decoding are Java objects like List, Map, etc. That would make it easier to use the library for the non-streaming case. Semantic tags could be handled in the encoding process by registering semantic tag handlers which would work on certain class/interface types. For example, a Date object could then automatically be tagged as such. Decoding would work similarly based on tag values.

**Comment by c-rack** [comment]
Thanks for asking!

For Lists and Maps, we basically already have that with CBOR arrays and maps, but without automatic conversion to `List<Long>` or `Map<String, String>` of course.

For semantic tags, I would like to keep this project standard-compliant, implementing only semantic tags that are registered at https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml

So if there is a CBOR tag for a Java Date object, we should implement it, otherwise not (until someone registers such a CBOR tag officially).

That said ... I really like your idea of _"semantic tag handlers"_, which could be registered on runtime, because they have two big benefits:

1. They allow users to define their own semantic tags without being restricted to the official ones
2. They allow us to keep the code base clean when implementing the official tags.

Any pull request in that direction is welcome! Just keep in mind that I have spend a great deal of time into a high code coverage score, so I would appreciate if pull requests do not lower it dramatically. :-)

**Comment by neothemachine** [comment]
Just to clarify, it sounds to me like you rather would put a high-level layer (sometimes called object mapper) in a separate library and keeping this one strictly to the low-level encoding/decoding, right?

My personal use case is that I'd like to encode packed arrays as detailed in this draft: https://tools.ietf.org/html/draft-jroatch-cbor-tags-03 It may become a standard but of course I want to use it now! :)

I had a quick look into the code base. As far as I see, the encoder already easily supports custom tags, you just have to derive from one of the base classes and set the tag, like in the LanguageTaggedString. In the decoder there is currently optional hard-coded logic for some official tags. This means it's just about the decoder side really for which the tag handlers would apply.

Since I'm only interested in encoding (doing decoding in JavaScript) I guess the best way would be if I create a library that has those packed array classes which can be used with your library while encoding. And about my other problem that I'd like to work on List's and Map's etc. that's probably yet another different library.

Does all what I said make sense? Did I miss anything?

**Comment by c-rack** [comment]
Thanks for the link to the RFC draft about typed arrays, very interesting! It would be great to have support for typed arrays directly in cbor-java and I will accept all PRs implementing it. Also, if you want to add general support for custom tag handlers in cbor-java, your PRs are also very welcome.

If you however decide to do it all in your own library, please leave a link here so others may find it.

**Comment by neothemachine** [comment]
Cool, good to hear. Since I'm not interesting in decoding in Java and 
don't have the time to implement both encodign and decoding I think it's 
still best if I put the things I need in a separate library for now. I 
could not create a pull request that makes sense currently, would be 
half baked. If someone decides to add both encoding and decoding of 
typed arrays to cbor-java then he can just steal the classes from my 
library and implement the missing parts. Once that happens, my library 
would become obsolete. I will post a link once I have something running.

**Comment by neothemachine** [comment]
First take on implementing this:
https://github.com/neothemachine/cbor-java-typedarray-encoder/blob/master/src/main/java/uk/ac/rdg/resc/cbor/typedarrays/model/TypedArray.java
It's untested but it should work if I don't have a typo with the tag numbers somewhere.
It's based on cbor-java's ByteString class. Does that look ok to you?

**Comment by neothemachine** [comment]
I created a first test which succeeds:
https://github.com/neothemachine/cbor-java-typedarray-encoder/blob/master/src/test/java/uk/ac/rdg/resc/cbor/typedarrays/model/TypedArrayTest.java

From my point of view I think I'm done. And it's actually quite easy to build the cbor structure with your own Map implementation, I hadn't realized that before.

**Comment by c-rack** [comment]
Looks good to me. Nice to see that your solution was that easy to build. :-)

So, do you think we can close this issue then?
We could re-open if someone wants to implement it in this project.

**Comment by neothemachine** [comment]
Yes, I'll close it. I also rename the issue title to include the typed arrays.

**Comment by neothemachine** [comment]
About the object mapper business. I just created a [small thing for myself](https://github.com/neothemachine/edal-json/blob/9f6694e774b800345920f6856475aea9f8255911/src/main/java/uk/ac/rdg/resc/edal/json/CBORRepresentation.java#L52). It's a single recursive function that maps an Object of supported type to a DataItem instance. This allowed me to use the same simple structures for serializing a thing to JSON but also to CBOR without changing any of my code. Note that this custom mapping code maps primitive numeric arrays to typed arrays. In general, this should be optional, as not all CBOR clients will be able to handle that, but then again, CBOR is typically used for specialized applications where you can demand certain things.

**Comment by c-rack** [comment]
:+1:
