### ISSUE TITLE
Remove .clone() for ByteString

### ISSUE THREAD

**Issue by neothemachine** [c-rack/cbor-java#18]
My use case is to encode big byte strings (which are then tagged as typed arrays), possibly up to 100MiB. I haven't profiled it yet, but from previous experience I can smell that the ByteString class will be one source of bottlenecks due to its use of array cloning within the constructor and also in getBytes(). In the ByteStringEncoder the getBytes() method is called and there is absolutely no reason to make a copy here. For the constructor, well, I would put more responsibilty into the user's hands and explicitly say in the javadoc that no copy is made, so the user has to make one himself if he wants to further use the byte array.

Removing the cloning operations will not only reduce memory usage spikes but also remove the time it would take to make the clone and also the effort that the garbage collector would have.

**Comment by c-rack** [comment]
The call to `clone()` is a consequence of our goal to pass **all** PMD, CPD and FindBugs tests.

Unfortunately, PMD considers your suggestion as a security problem:
http://pmd.sourceforge.net/pmd-4.3.0/rules/sunsecure.html

I would merge a PR that removes the `clone()` call while preserving the PMD tests passing, for example by providing a proper exclusion of those tests. :-)

**Comment by neothemachine** [comment]
OK I understand, I will submit a pull request tomorrow or so. Thanks!

**Comment by neothemachine** [comment]
I just had a look at how to configure PMD and it seems to be quite tricky to [exclude a rule](http://stackoverflow.com/questions/11645443/can-you-exclude-a-source-file-for-a-specific-pmd-rule) for a specific file or even method. I was hoping for some kind of annotation but that's not how it works apparently. I'm afraid I won't have the time to look into that unfortunately.

Since the encoder is hardwired to that specific ByteString class (and not an interface) I also can't just extend or copy a modified version into my codebase as a quick fix. With an `extends` I would still have to use the parent constructor which does the cloning.

Any suggestion?

**Comment by c-rack** [comment]
I'll take care about that :-)

**Comment by neothemachine** [comment]
Thanks! :)

**Comment by c-rack** [comment]
Hope to find the time for an official release (also on maven central) today
