### ISSUE TITLE
Add Array(int initialCapacity) constructor

### ISSUE THREAD

**Issue by neothemachine** [c-rack/cbor-java#19]
There's currently no way to create an Array with a hint of the capacity it will have. Since Map already has such a constructor, Array should have it too since it can improve performance in cases where the size is known.

**Comment by c-rack** [comment]
:+1:

**Comment by c-rack** [comment]
Version 0.7 with fixes for #18 and #19 has been published to Maven central:
https://search.maven.org/#artifactdetails|co.nstant.in|cbor|0.7|jar
