### ISSUE TITLE
cbor 0.7 on maven repo is out of sync

### ISSUE THREAD

**Issue by charybr** [c-rack/cbor-java#47]
Hi,

Appears that cbor 0.7 jar in maven repo (https://repo.maven.apache.org) is different from what we get on building 0.7 from source code.

The issue notificed is: 
Using cbor 0.7 downloaded from maven repo gives boolean as SIMPLE_VALUE during decode. 
Where as using cbor 0.7 built from source code gives boolean as TRUE or FALSE during decode.

Please update cbor 0.7 on maven repo.

Best Regards,
Chary

**Comment by c-rack** [comment]
Actually, source should be 0.8-SNAPSHOT, not 0.7. I will fix that asap.

**Comment by charybr** [comment]
Thanks!
