### ISSUE TITLE
Reaction to invalid CBOR

### ISSUE THREAD

**Issue by andreasWallner** [c-rack/cbor-java#49]
Looking at the code it seems that a few cases of invalid CBOR do not result on exceptions being thrown, e.g.

```
    @Test(expected = CborException.class)
    public void shouldThrowOnIncompleteMap() throws CborException {
    	byte[] bytes = new byte[] {(byte) 0xa2, 0x01, 0x02};
    	CborDecoder.decode(bytes);
    }
    
    @Test(expected = CborException.class)
    public void shouldThrowOnIncompleteArray() throws CborException {
    	byte[] bytes = new byte[] {(byte) 0xc2, 0x01 };
    	CborDecoder.decode(bytes);
    }
```

Is this for a specific reason, or did this just never come up? I wanted to use the library to tests clients for a protocol that uses CBOR to encode data, and would need to reject invalid serializations.

The current behaviour is also a bit misleading, since the decode functions' documentation lists CborExcpetion as being thrown "if decoding failed".

**Comment by c-rack** [comment]
@andreasWallner Thanks for reporting!
This just never came up.
Any PR to fix this would be appreciated and will be merged quickly.

**Comment by andreasWallner** [comment]
OK, I'm happy to do the change, give me 2-3 days ;-)

**Comment by andreasWallner** [comment]
sorry pressed the wrong button...
