### ISSUE TITLE
Builder can't be used to construct IL map inside map

### ISSUE THREAD

**Issue by andreasWallner** [c-rack/cbor-java#51]
Currently the MapBuilder can't be used to start an indefinite length map, since there is no startMap function. Would you be against adding that?

**Comment by andreasWallner** [comment]
E.g. construct something like

    BF       # map(*)
       01    # unsigned(1)
       BF    # map(*)
          01 # unsigned(1)
          01 # unsigned(1)
          FF # primitive(*)
       FF    # primitive(*)

**Comment by c-rack** [comment]
No, that would be a nice enhancement.

**Comment by andreasWallner** [comment]
merged with PR #53
