### ISSUE TITLE
Detect duplicate keys in maps

### ISSUE THREAD

**Issue by andreasWallner** [c-rack/cbor-java#52]
When parsing encoded CBOR, is there a way to detect duplicate keys in maps? For e.g.

    A2 0101 0102

I'd need to be able to detect this scenario (as this is prohibited for the communication protocol I'm working with). Do you see a way to do that? 
Looking at the current code, the element is just replaced in the map, would you be open to e.g. make this behavior configurable?

**Comment by c-rack** [comment]
Yes, feel free to submit a PR.

**Comment by andreasWallner** [comment]
merged with #54
