### ISSUE TITLE
nstant.in.cbor.CborException: Reserved additional information

### ISSUE THREAD

**Issue by naveenkumarmarri** [c-rack/cbor-java#58]
Hi,

I'm trying to decode cbor.
When I'm decoding i'm getting the following error.
`
co.nstant.in.cbor.CborException: Reserved additional information
	at co.nstant.in.cbor.decoder.AbstractDecoder.getLength(AbstractDecoder.java:70)
	at co.nstant.in.cbor.decoder.MapDecoder.decode(MapDecoder.java:19)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:136)
	at co.nstant.in.cbor.decoder.MapDecoder.decodeInfinitiveLength(MapDecoder.java:32)
	at co.nstant.in.cbor.decoder.MapDecoder.decode(MapDecoder.java:21)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:136)
	at co.nstant.in.cbor.CborDecoder.decode(CborDecoder.java:89)
	at org.eclipse.californium.examples.HelloWorldServer$1.handlePUT(HelloWorldServer.java:64)
	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:218)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:85)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:162)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:237)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:218)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:97)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveRequest(CoapEndpoint.java:736)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:665)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$800(CoapEndpoint.java:628)
	at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:642)
	at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:804)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
I'm getting cbor data in string and I'm converting to byte array using
`content.getBytes()`
Following is the code snippet for the same.

`
	ByteArrayInputStream bais = new ByteArrayInputStream(content.getBytes());
       	 	List<DataItem> dataItems;
			try {
				dataItems = new CborDecoder(bais).decode();
				for(DataItem dataItem : dataItems) {
	       	 	  System.out.println(dataItem);
	       	 	}
			} catch (CborException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
`

Am I missing something here?

**Comment by c-rack** [comment]
@naveenkumarmarri could you please provide a minimal example to reproduce this issue? Please also include the bytes you are trying to decode.

**Comment by naveenkumarmarri** [comment]
Following is byte array

`95,27,20,-17,-65,-67,-17,-65,-67,101,118,97,108,117,101,-17,-65,-67,64,77,38,-17,-65,-67,-17,-99,-78,45,105,101,118,101,110,116,84,121,112,
112,101,97,52,103,115,117,98,106,101,99,116,107,116,101,109,112,101,114,97,116,117,114,101`

Following is the code I'm trying to use. I'm listening on a coap port for incoming packets and decoding them using cbor

`CoapServer server = new CoapServer(5555);
            server.add(new CoapResource("helloWorld")  {
       		 @Override
       	 	   public void handlePUT(CoapExchange exchange) {
       	 		 content = exchange.getRequestText();
       	 		 exchange.respond(ResponseCode.CHANGED);
       	 		byte [] bytes = content.getBytes();
       	 		for(Byte b :bytes)
       	 			System.out.println(b);
       	 		ByteArrayInputStream bais = new ByteArrayInputStream(content.getBytes());
       	 		List<DataItem> dataItems; 
       	 		try { dataItems = new CborDecoder(bais).decode(); 
       	 		for(DataItem dataItem : dataItems) { System.out.println(dataItem); } 
       	 		System.out.println(bais);
       	 		} 
       	 		catch (CborException e) 
       	 		{ // TODO Auto-generated catch block e.printStackTrace(); }
       	 			//System.out.println(e.getMessage());
       	 		}
       	 		System.out.println(content);
   	  	   }
   	    }); 
            server.start();`

Please let me know if I needs to change something

**Comment by andreasWallnerIFX** [comment]
Converted to hex (easier for most tools...) this is

    5f 1b 14 ef bf bd ef bf bd 65 76 61 6c 75 65 ef bf bd 40 4d 26 ef bf bd ef 9d b2 2d 69 65 76 65 6e 74 54 79 70 70 65 61 34 67 73 75 62 6a 65 63 74 6b 74 65 6d 70 65 72 61 74 75 72 65

Looking at that it looks like invalid data to me: `5F` starts an indefinite length byte string. The first element in the indefinite length byte string is an unsigned integer, which is not allowed inside a IL byte string.

The error message could be a bit better, but it seems to me your input data is invalid.

**Comment by naveenkumarmarri** [comment]
HI,
Following is the byte string i'm getting in Hex format.
```` EF BF BD 62 74 73 1B 00 00 01 5F 5A 51 C3 A8 65 76 61 6C 75 65 EF BF BD 40 4C EF BF BD EF BF BD 68 72 EF BF BD 69 65 76 65 6E 74 54 79 70 65 61 32 67 73 75 62 6A 65 63 74 6B 74 65 6D 70 65 72 61 74 75 72 65 ````
Still I'm getting reserved additional information error

**Comment by c-rack** [comment]
@naveenkumarmarri could you please provide the code to generate this byte string?

**Comment by naveenkumarmarri** [comment]
````
  */
    public static void main(String[] args) {
        
       // try {

            // create server
            HelloWorldServer server = new HelloWorldServer();
            // add endpoints on all IP addresses
            server.addEndpoints();
           // server.start();
    	 
            server.add(new CoapResource("helloWorld")  {
       		 @Override
       	 	   public void handlePUT(CoapExchange exchange) {
       	 		 content = exchange.getRequestText();
       	 		 exchange.respond(ResponseCode.CHANGED);
       	 		 
       	 		 byte [] b = (content.getBytes());
       	 		 System.out.println("----------------------");
       	 		StringBuilder sb = new StringBuilder();
	       	     for (byte bs : b) {
	       	         sb.append(String.format("%02X ", bs));
	       	     }
	       	     System.out.println(sb.toString());
       	 		ByteArrayInputStream bais = new ByteArrayInputStream(content.getBytes());
       	 		List<DataItem> dataItems;
       	 		try 
       	 		{ 
       	 			dataItems = new CborDecoder(bais).decode(); 
       	 			for(DataItem dataItem : dataItems) 
       	 				System.out.println(dataItem); 
       	 		CborDecoder decoder = new CborDecoder(bais);
        		DataItem b_1 = decoder.decodeNext();

        		
        		Tag tag = b_1.getTag();
        		System.out.println(tag.getValue());
       	 		} 
       	 	
       	 		 
       	 		catch (CborException e) { System.out.println(e.getMessage()); 
       	 			}
       	 		
   	  	   }
   	    }); 
````

**Comment by c-rack** [comment]
@naveenkumarmarri thanks, but not what I was looking for (my question was not precise enough).
You posted sourcecode that receives some data that fails to decode. I wanted to see the code that actually produces that data *before sending* to your server.

Could you also provide a minimal example with encoding and (failing) decoding, but without any network transmission? This way, we can exclude a bug in client/server implementation. Thanks.

**Comment by naveenkumarmarri** [comment]
The CBOR encoding is done from a node application and  streamed to a java application using CoAP protocol where the decoding is being done.
Would you like to see how the encoding is done from the node js side?

**Comment by andreasWallner** [comment]
@naveenkumarmarri It seems something is going wrong on either the encoding side or transmission, judging from the latest CBOR data that you posted.

The `EF BF BD` in the beginning (and inbetween) doesn't really make sense:
* `EF` is an item with Major Type 5, Additional Info 15. This is a "simple value" that is currently not assigned by the spec - not a problem, but also doesn't make too much sense.
* `BF` is an indefinite length map - no problem
* `BD` again MT 5, but Additional Info is 29. Additional Info of 29 is reserved for future use (compare with the CBOR spec, chapter 2, 2nd paragraph. This item is therefore invalid - which is what the meaning of the Exception is that you are getting.
* Afterwards there are some items that seem fine ("ts", some integer, "value") after which we again see this `EF BF BD` sequence. (which you can see after playing around a bit with cbor.me)

So as explained above: The exception that you are seeing is telling you that what you are trying to decode is not valid CBOR.

**Comment by naveenkumarmarri** [comment]
@andreasWallner I  want to extract the values starting from the "ts" tag.
I'm able to decode the cbor in nodejs.

**Comment by andreasWallner** [comment]
@naveenkumarmarri Then the nodejs library that you are using either has a bug or ignores invalid data. You can check with e.g. cbor.me that what you posted 6 days ago is not valid CBOR. To get it to parse with this library you'll have to fix your encoding.

**Comment by c-rack** [comment]
@naveenkumarmarri yes, a minimal example source that shows the encoding (even in nodejs) would help.

**Comment by naveenkumarmarri** [comment]
````
const send_payload_obj=(t,v,e,s)=>{
            const payload = {ts: t, value: v, eventType: e, subject: s};
            if (example_request.encoding==='cbor') {
              req.end(cbor.encode(payload));
            } else {
              req.end(JSON.stringify(payload));
            }
          };
````

**Comment by c-rack** [comment]
@naveenkumarmarri that is only a code snippet without any valuable information. What I was asking for is a minimal but complete example how the data is CBOR-encoded (so that we can run it on our own), for example something like (I am not a JS expert):
```javascript
var cbor = require("cbor");
var data = [1,2,3];
var encoded = cbor.encode(data);
printAsHex(encoded);
// Output: 0xXX, 0xYY, 0xZZ
```
