### ISSUE TITLE
new release to maven please

### ISSUE THREAD

**Issue by uptimestar** [c-rack/cbor-java#59]
Hi, can you push another release to maven. Last one is from 2015 and there are changes since then.

**Comment by c-rack** [comment]
@uptimestar sorry for the delay, hope to find the time to do a release this weekend

**Comment by c-rack** [comment]
Just for reference, version 0.8 has been released:
http://search.maven.org/#artifactdetails%7Cco.nstant.in%7Ccbor%7C0.8%7Cjar
