### ISSUE TITLE
Issue while encoding Json string

### ISSUE THREAD

**Issue by Raveesh** [c-rack/cbor-java#63]
Hi,
Apologies if the question is not clear. I am a newbie to cbor.
My scenario is as follows: 
We are building a large IOT platform where we need to communicate with devices from the cloud. We have a reqirement to  push configurations to the devices. The configurations essentially are in the [JsonApi Spec format](http://jsonapi.org/format/). So, essentially, the platform exposes REST api's to accept these configuration json as a String entity which are then cbor encoded and sent to the devices. Our typical json string would look like 

`{"data": {"id": "15", "type": "configs", "meta": {"t": "2015-03-25T13:59:19Z", "val": 1234}, "attributes": {"key": {"k1": "2015-03-25T13:59:19Z"}, "k2": {"key2": "val2", "key3": "val3", "key4": 1}, "meta": {"version": ["1.2"]}}`

Now, since this is a string , the cbor library encodes the entire payload as MajorType 2 or 3. However, what we really need is to identify inner attributes such as "val" which is of integer type, or attributes which can contain map or other sub objects. In this case they are all considered as a String literal type and not encoded. Is there a way for the library to identify and encode individual values within a json String?

My sample Code: 
```
import co.nstant.in.cbor.CborBuilder;
import co.nstant.in.cbor.CborEncoder;
import co.nstant.in.cbor.CborException;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class TestCbor {
    public static void main(String[] args) throws CborException, IOException {
        String s = "{\"data\":{\"id\":\"15\",\"type\":\"configs\"," +
                "\"meta\":{\"t\":\"2015-03-25T13:59:19Z\",\"val\":1234}," +
                "\"attributes\":{\"key\":{\"k1\":\"2015-03-25T13:59:19Z\"}," +
                "\"k2\":{\"key2\":\"val2\",\"key3\":\"val3\",\"key4\":1}," +
                "\"meta\":{\"version\":[\"1.2\"]}}}}";

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        new CborEncoder(baos).encode(new CborBuilder()
                .add(s).build());
        byte[] encodedBytes = baos.toByteArray();
        Files.write(Paths.get("output.cbor"), encodedBytes);

    }
}

```
File Output 
`x�{"data":{"id":"15","type":"configs","meta":{"t":"2015-03-25T13:59:19Z","val":1234},"attributes":{"key":{"k1":"2015-03-25T13:59:19Z"},"k2":{"key2":"val2","key3":"val3","key4":1},"meta":{"version":["1.2"]}}}}`

I tried to run the cbor encoding using the nodejs library . I am trying to get the same output in java as well . 
Nodejs output 
`¡ddata¤bidb15dtypegconfigsdmeta¢att2015-03-25T13:59:19Zcval^Y^DÒjattributes£ckey¡bk1t2015-03-25T13:59:19Zbk2£dkey2dval2dkey3dval3dkey4^Admeta¡gversion<81>c1.2
`

**Comment by c-rack** [comment]
@Raveesh cbor-java is only an encoder and decoder library for CBOR format. It does not understand JSON. You put in a string, so it will encode it as a string. In order to encode your JSON to CBOR, you either need to write a JsonCborEncoder for yourself or use another library that is capable to do that.
