### ISSUE TITLE
Difficult to decode byte array e.g. byte[]

### ISSUE THREAD

**Issue by bosco-ferrao** [c-rack/cbor-java#64]
Found it difficult to use byte array e.g. byte[]. One can encode but how to decode?

**Comment by c-rack** [comment]
@bosco-ferrao I have just commited an example code:
https://github.com/c-rack/cbor-java/blob/master/src/test/java/co/nstant/in/cbor/decoder/ByteStringDecoderTest.java#L79-L98

Please close this issue if that was what you are looking for.

**Comment by c-rack** [comment]
Closed due to inactivity.

@bosco-ferrao feel free to re-open if there is still something unclear.
