### ISSUE TITLE
Compatibility with peteroupc library(https://github.com/peteroupc/CBOR-Java)

### ISSUE THREAD

**Issue by jas-singh14** [c-rack/cbor-java#66]
We have a situation where client has to use peteroupc CBOR (https://github.com/peteroupc/CBOR-Java) library whereas server has to use c-rack CBOR library(https://github.com/c-rack/cbor-java)
Although both comply to RFC 7049. but wanted to doubly sure if there are any potential challenges/issues w.r.t to the above mentioned arrangement.

**Comment by c-rack** [comment]
@jas-singh14 Please see the issues tab for any open issues of this project. Regarding compatibility with other libraries, you may have to either test this by yourself or pay someone to do this for you.

Closing this issue as it does not describe a problem. Feel free to re-open if needed.
