### ISSUE TITLE
Infinite loop during decode

### ISSUE THREAD

**Issue by fatboyfitz** [c-rack/cbor-java#78]
Decoding certain byte strings cause an infinite loop in MapDecoder.decodeInfinitiveLength(). The issue is that the input stream is exhausted, so decodeNext() always returns null. Null is never checked for an exit condition to the infinite loop. The data is not well formed CBOR, I realize, but I assumed that the decoder should throw in exception for malformed input.

Below is a base64 encoded byte string which triggers the problem and example code which shows the issue.

v0W5jpZleP8=
[CBORInfiniteLoop.java.gz](https://github.com/c-rack/cbor-java/files/2270804/CBORInfiniteLoop.java.gz)

**Comment by c-rack** [comment]
@fatboyfitz Thanks for reporting. Could you please send a pull request to fix it? I'll merge it quickly and release a new version then.

**Comment by c-rack** [comment]
@fatboyfitz You could first send a pull request which introduces a failing unit test. I guess that should be easy. Then, another pull request (by you or by me) can provide the actual fix.

Quickly scanning the code, we already have a detection for unexpected end of streams:
https://github.com/c-rack/cbor-java/blob/master/src/main/java/co/nstant/in/cbor/decoder/MapDecoder.java#L37-L39

Maybe your unit test reveals why this is not working.

**Comment by fatboyfitz** [comment]
My apologies - this was fixed in a later release than I was testing against. The github releases page only shows up to 0.7, which is what I was using. The latest on master has the check you mention and does indeed catch this problem.

**Comment by c-rack** [comment]
You're welcome!
