### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by divegeek** [c-rack/cbor-java#97]
Hi, there are a couple of improvements and bugfixes in 0.9 that I need, but 0.8 is the latest version in the public repositories, so 0.9 isn't easy to specify as a dependency.

**Comment by divegeek** [comment]
Hmm.  Just noticed that 0.9 isn't release.  So this really should be "release 0.9", please.  :-)

Updated accordingly.

**Comment by chaingrok** [comment]
Hi, I concur : 0.9 is not release on mvnrepository, do you plan to do it?

**Comment by divegeek** [comment]
Can I release it on mvnrepository?  I don't know how, or if I have permission.  I'd think only someone who "owns" the project in some sense can, but I've never worked with mvnrepository so I don't know.

**Comment by c-rack** [comment]
@divegeek I'll do the release today and update once it's in the mvn repo

**Comment by divegeek** [comment]
Thank you very much!  I'll update the copy in Android once you do.

**Comment by c-rack** [comment]
@divegeek @chaingrok Version 0.9 is now in available in Maven Central. Sorry for the delay and any inconvenience!

**Comment by divegeek** [comment]
Thanks!
